exam_name_biogne

WITH structurally_cleaned AS (
    SELECT distinct
        exam_name AS exam_name_raw,
        TRIM(
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    REGEXP_REPLACE(
                        REGEXP_REPLACE(TRIM(exam_name), '\\s+', ' '),
                        ',(?=\\S)', ', '
                    ),
                    '\\s*[:?]+\\s*$', ''
                ),
                '^[\\-\\*\\.>%]+\\s*|\\s*[\\-\\*\\.>%]+$', ''
            )
        ) AS exam_name_cleaned
    FROM biogen_consolidated.examination
)
SELECT
    exam_name_raw,
    CASE LOWER(exam_name_cleaned)
        WHEN '' THEN ''
        WHEN '(see activity/participation limitations below)' THEN '(See Activity/Participation Limitations Below)'
        WHEN '(see goals listed below)' THEN '(See Goals Listed Below)'
        WHEN '/s/ to /z/ ratio' THEN '/S/ to /Z/ Ratio'
        WHEN '1' THEN '1'
        WHEN '10' THEN '10'
        WHEN '10th cranial nerve' THEN '10th Cranial Nerve'
        WHEN '11' THEN '11'
        WHEN '11th cranial nerve' THEN '11th Cranial Nerve'
        WHEN '12th cranial nerve' THEN '12th Cranial Nerve'
        WHEN '1st cranial nerve (rose, orange, peppermint)' THEN '1st Cranial Nerve (Rose, Orange, Peppermint)'
        WHEN '2' THEN '2'
        WHEN '25 foot ta' THEN '25 Foot TA'
        WHEN '2nd cranial nerve' THEN '2nd Cranial Nerve'
        WHEN '3' THEN '3'
        WHEN '3rd, 4th and 6th cranial nerve' THEN '3rd, 4th and 6th Cranial Nerve'
        WHEN '4' THEN '4'
        WHEN '5' THEN '5'
        WHEN '5th cranial nerve' THEN '5th Cranial Nerve'
        WHEN '6' THEN '6'
        WHEN '7' THEN '7'
        WHEN '7th cranial nerve' THEN '7th Cranial Nerve'
        WHEN '8' THEN '8'
        WHEN '8th cranial nerve' THEN '8th Cranial Nerve'
        WHEN '9' THEN '9'
        WHEN '9 hole peg test (nhpt)' THEN '9 Hole Peg Test (NHPT)'
        WHEN '9th cranial nerve' THEN '9th Cranial Nerve'
        WHEN 'abdomen' THEN 'Abdomen'
        WHEN 'abdominal examination' THEN 'Abdominal Examination'
        WHEN 'abducens' THEN 'Abducens'
        WHEN 'abnormal/psychotic thoughts' THEN 'Abnormal/Psychotic Thoughts'
        WHEN 'abstraction' THEN 'Abstractions'
        WHEN 'abstractions' THEN 'Abstractions'
        WHEN 'accessory' THEN 'Accessory'
        WHEN 'acclimatization' THEN 'Acclimatization'
        WHEN 'acoustic' THEN 'Acoustic'
        WHEN 'action tremor-left' THEN 'Action Tremor-Left'
        WHEN 'action tremor-right' THEN 'Action Tremor-Right'
        WHEN 'activities' THEN 'Activities'
        WHEN 'activity' THEN 'Activity'
        WHEN 'activity limitations' THEN 'Activity Limitations'
        WHEN 'additional cognitive' THEN 'Additional Cognitive'
        WHEN 'additional comments' THEN 'Additional Comments'
        WHEN 'additional observations' THEN 'Additional Observations'
        WHEN 'adnexa' THEN 'Adnexa'
        WHEN 'adventitious movements' THEN 'Adventitious Movements'
        WHEN 'affect' THEN 'Affect'
        WHEN 'alertness' THEN 'Alertness'
        WHEN 'alignment' THEN 'Alignment'
        WHEN 'also present' THEN 'Also Present'
        WHEN 'also present during encounter' THEN 'Also Present During Encounter'
        WHEN 'alt' THEN 'ALT'
        WHEN 'alteration in gait/equilibrium' THEN 'Alteration in Gait/Equilibrium'
        WHEN 'alteration in mentation' THEN 'Alteration in Mentation'
        WHEN 'alteration in speech' THEN 'Alteration in Speech'
        WHEN 'ambulation' THEN 'Ambulation'
        WHEN 'ankle' THEN 'Ankle'
        WHEN 'ankles and feet' THEN 'Ankles and Feet'
        WHEN 'anorectal/perineum' THEN 'Anorectal and Perineum'
        WHEN 'anus/perineum' THEN 'Anus and Perineum'
        WHEN 'anxiety screening' THEN 'Anxiety Screening'
        WHEN 'aphasia' THEN 'Aphasia'
        WHEN 'appearance' THEN 'Appearance'
        WHEN 'arise chair' THEN 'Arise Chair'
        WHEN 'arizona battery cognitive-communication disorders-2 (abcd-2)' THEN 'Arizona Battery Cognitive-Communication Disorders-2 (ABCD-2)'
        WHEN 'arm extension' THEN 'Arm Extension'
        WHEN 'as a passenger in a car for an hour without a break' THEN 'As a Passenger in a Car for an Hour Without a Break'
        WHEN 'ask for the 3 objects from registration score' THEN 'Ask for the 3 Objects from Registration Score'
        WHEN 'aspirin or antiplatelet not given' THEN 'Aspirin or Antiplatelet Not Given'
        WHEN 'assess level of consciousness along a continuum' THEN 'Assess Level of Consciousness Along a Continuum'
        WHEN 'assessment of dysphagia' THEN 'Assessment of Dysphagia'
        WHEN 'assessment of motor function' THEN 'Assessment of Motor Function'
        WHEN 'assistive devices' THEN 'Assistive Devices'
        WHEN 'attention' THEN 'Attention Span'
        WHEN 'attention and concentration' THEN 'Attention and Concentration'
        WHEN 'attention span' THEN 'Attention Span'
        WHEN 'attention span and concentration' THEN 'Attention Span and Concentration'
        WHEN 'attention span and remote memory' THEN 'Attention Span and Remote Memory'
        WHEN 'attention span/concentration' THEN 'Attention Span/Concentration'
        WHEN 'attention/concentration' THEN 'Attention and Concentration'
        WHEN 'attitude' THEN 'Attitude'
        WHEN 'attitude toward provider' THEN 'Attitude Toward Provider'
        WHEN 'audiologic evaluation' THEN 'Audiologic Evaluation'
        WHEN 'auditory' THEN 'Auditory'
        WHEN 'auditory comprehension' THEN 'Auditory Comprehension'
        WHEN 'auditory hallucinations' THEN 'Auditory Hallucinations'
        WHEN 'auscultation of heart' THEN 'Auscultation of Heart'
        WHEN 'average hours of sleep per night' THEN 'Average Hours of Sleep Per Night'
        WHEN 'awake' THEN 'Awake'
        WHEN 'b12' THEN 'B12'
        WHEN 'babinski' THEN 'Babinski'
        WHEN 'babinski reflex' THEN 'Babinski Reflex'
        WHEN 'back' THEN 'Back'
        WHEN 'back exam' THEN 'Back Exam'
        WHEN 'balance' THEN 'Balance'
        WHEN 'barriers to adherence' THEN 'Barriers to Adherence'
        WHEN 'batteries' THEN 'Batteries'
        WHEN 'behavior' THEN 'Behavior'
        WHEN 'behavioral observations during phonation' THEN 'Behavioral Observations During Phonation'
        WHEN 'bell''s palsy' THEN 'Bell''s Palsy'
        WHEN 'benadryl' THEN 'Benadryl'
        WHEN 'biceps, triceps, brachioradialis, knees' THEN 'Biceps, Triceps, Brachioradialis, Knees'
        WHEN 'bilirubin' THEN 'Bilirubin'
        WHEN 'bladder' THEN 'Bladder'
        WHEN 'blepharospasm' THEN 'Blepharospasm'
        WHEN 'blood' THEN 'Blood'
        WHEN 'blood return' THEN 'Blood Return'
        WHEN 'bmi classification' THEN 'BMI Classification'
        WHEN 'bmi follow up not documented' THEN 'BMI Follow Up Not Documented'
        WHEN 'bmi not documented' THEN 'BMI Not Documented'
        WHEN 'body bradykinesia' THEN 'Body Bradykinesia'
        WHEN 'body fat' THEN 'Body Fat'
        WHEN 'boston diagnostic aphasia examination-3 (bdae-3)' THEN 'Boston Diagnostic Aphasia Examination-3 (BDAE-3)'
        WHEN 'boston naming test (bnt)' THEN 'Boston Naming Test (BNT)'
        WHEN 'bowel & bladder function' THEN 'Bowel and Bladder Functions'
        WHEN 'bowel and bladder functions' THEN 'Bowel and Bladder Functions'
        WHEN 'bp management' THEN 'BP Management'
        WHEN 'bradykinesia' THEN 'Bradykinesia'
        WHEN 'bragard''s test' THEN 'Bragard''s Test'
        WHEN 'brainstem functions' THEN 'Brainstem Functions'
        WHEN 'breast' THEN 'Breasts'
        WHEN 'breasts' THEN 'Breasts'
        WHEN 'bulk' THEN 'Bulk'
        WHEN 'c spine exam' THEN 'C Spine Exam'
        WHEN 'caffeine' THEN 'Caffeine'
        WHEN 'calculations' THEN 'Calculations'
        WHEN 'caloric function tests' THEN 'Caloric Function Tests'
        WHEN 'candidacy' THEN 'Candidacy'
        WHEN 'cape-v' THEN 'CAPE-V'
        WHEN 'cardiac' THEN 'Cardiac Exam'
        WHEN 'cardiac exam' THEN 'Cardiac Exam'
        WHEN 'cardiovascular' THEN 'Cardiovascular Examination'
        WHEN 'cardiovascular examination' THEN 'Cardiovascular Examination'
        WHEN 'cardiovascular system' THEN 'Cardiovascular System'
        WHEN 'care planning i' THEN 'Care Planning I'
        WHEN 'caregiver needs/knowledge/social supports' THEN 'Caregiver Needs/Knowledge/Social Supports'
        WHEN 'carotid ascultation' THEN 'Carotid Ascultation'
        WHEN 'carotid auscultation' THEN 'Carotid Auscultation'
        WHEN 'carotid doppler' THEN 'Carotid Doppler'
        WHEN 'carotids' THEN 'Carotids'
        WHEN 'case management' THEN 'Case Management'
        WHEN 'cc' THEN 'CC'
        WHEN 'central neurologic examination' THEN 'Central Neurologic Examination'
        WHEN 'cerebellar' THEN 'Cerebellar Examination'
        WHEN 'cerebellar examination' THEN 'Cerebellar Examination'
        WHEN 'cerebellar functions' THEN 'Cerebellar Functions'
        WHEN 'cerebellar signs' THEN 'Cerebellar Signs'
        WHEN 'cerebellar testing grossly/intact' THEN 'Cerebellar Testing Grossly/Intact'
        WHEN 'cerebral functions' THEN 'Cerebral Functions'
        WHEN 'certification of plan of care' THEN 'Certification of Plan of Care'
        WHEN 'certification/benefits' THEN 'Certification/Benefits'
        WHEN 'cervical' THEN 'Cervical'
        WHEN 'cervical compression test' THEN 'Cervical Compression Test'
        WHEN 'cervical dystonia' THEN 'Cervical Dystonia'
        WHEN 'cervical spine' THEN 'Cervical Spine Examination'
        WHEN 'cervical spine exam' THEN 'Cervical Spine Examination'
        WHEN 'cervical testing' THEN 'Cervical Testing'
        WHEN 'cervix' THEN 'Cervix'
        WHEN 'changes in the patient''s condition that now requires the use of a power mobility device' THEN 'Changes in the Patient''s Condition That Now Requires the Use of a Power Mobility Device'
        WHEN 'chaperone' THEN 'Chaperone'
        WHEN 'chaperoned by' THEN 'Chaperoned by'
        WHEN 'chart' THEN 'Chart'
        WHEN 'chest' THEN 'Chest'
        WHEN 'chest/ lungs' THEN 'Chest and Lungs'
        WHEN 'chest/lungs' THEN 'Chest and Lungs'
        WHEN 'chewing/swallowing' THEN 'Chewing/Swallowing'
        WHEN 'chlortrimeton' THEN 'Chlortrimeton'
        WHEN 'ci mapping' THEN 'CI Mapping'
        WHEN 'clinical dementia rating (cdr)' THEN 'Clinical Dementia Rating (CDR)'
        WHEN 'clinical reports reviewed' THEN 'Clinical Reports Reviewed'
        WHEN 'clinical trial' THEN 'Clinical Trial'
        WHEN 'clockface' THEN 'Clockface'
        WHEN 'cn' THEN 'CN'
        WHEN 'cognition' THEN 'Cognition'
        WHEN 'cognition and comprehension' THEN 'Cognition and Comprehension'
        WHEN 'cognitive baseline' THEN 'Cognitive Baseline'
        WHEN 'cognitive evaluation and review of results' THEN 'Cognitive Evaluation and Review of Results'
        WHEN 'cognitive impairment assessment' THEN 'Cognitive Impairment Assessment'
        WHEN 'cognitive linguistic quick test + (clqt+)' THEN 'Cognitive Linguistic Quick Test + (CLQT+)'
        WHEN 'cognitive testing' THEN 'Cognitive Testing'
        WHEN 'color' THEN 'Color'
        WHEN 'communication' THEN 'Communication'
        WHEN 'comorbidities impacting the plan of care' THEN 'Comorbidities Impacting the Plan of Care'
        WHEN 'comorbidities that affect occupational performance' THEN 'Comorbidities That Affect Occupational Performance'
        WHEN 'comprehension' THEN 'Comprehension'
        WHEN 'concentration' THEN 'Attention Span'
        WHEN 'connectivity' THEN 'Connectivity'
        WHEN 'consent signed' THEN 'Consent Signed'
        WHEN 'constitutional' THEN 'Constitutional'
        WHEN 'constructional tasks;' THEN 'Constructional Tasks;'
        WHEN 'contact method' THEN 'Contact Method'
        WHEN 'coordination' THEN 'Coordination and Gait'
        WHEN 'coordination and gait' THEN 'Coordination and Gait'
        WHEN 'coordination examination' THEN 'Coordination Examination'
        WHEN 'coordination/cerebellar' THEN 'Coordination/Cerebellar'
        WHEN 'copy the design (polygons) below score' THEN 'Copy the Design (Polygons) Below Score'
        WHEN 'cortical functions' THEN 'Cortical Functions'
        WHEN 'cortical release signs' THEN 'Cortical Release Signs'
        WHEN 'cortical sensory is' THEN 'Cortical Sensory Is'
        WHEN 'cortical/cognitive functions' THEN 'Cortical/Cognitive Functions'
        WHEN 'counting 1-10' THEN 'Counting 1-10'
        WHEN 'coupling' THEN 'Coupling'
        WHEN 'cranial nerve examination: ii' THEN 'Cranial Nerve Examination: II'
        WHEN 'cranial nerve i' THEN 'Cranial Nerve I'
        WHEN 'cranial nerve ii' THEN 'Cranial Nerve II'
        WHEN 'cranial nerve iii, iv, and vi' THEN 'Cranial Nerve III, IV, and VI'
        WHEN 'cranial nerve iii, iv, vi' THEN 'Cranial Nerve III, IV, and VI'
        WHEN 'cranial nerve ix' THEN 'Cranial Nerve IX'
        WHEN 'cranial nerve ix and x' THEN 'Cranial Nerve IX and X'
        WHEN 'cranial nerve ix, x' THEN 'Cranial Nerve IX and X'
        WHEN 'cranial nerve v' THEN 'Cranial Nerve V'
        WHEN 'cranial nerve vii' THEN 'Cranial Nerve VII'
        WHEN 'cranial nerve viii' THEN 'Cranial Nerve VIII'
        WHEN 'cranial nerve xi' THEN 'Cranial Nerve XI'
        WHEN 'cranial nerve xii' THEN 'Cranial Nerve XII'
        WHEN 'cranial nerves' THEN 'Cranial Nerves'
        WHEN 'cranial nerves ii - xii' THEN 'Cranial Nerve II-XII'
        WHEN 'cranial nerves ii, iii' THEN 'Cranial Nerves II, III'
        WHEN 'cranial nerves ii-xii' THEN 'Cranial Nerve II-XII'
        WHEN 'cranial nerves iii, iv, vi' THEN 'Cranial Nerve III, IV, and VI'
        WHEN 'cranial nerves ix, x' THEN 'Cranial Nerve IX and X'
        WHEN 'cranial nerves ix, x, xi' THEN 'Cranial Nerves IX, X, XI'
        WHEN 'cranial nerves xi, xii' THEN 'Cranial Nerves XI, XII'
        WHEN 'crepitus' THEN 'Crepitus'
        WHEN 'cul-de-sac' THEN 'Cul-de-sac'
        WHEN 'cv' THEN 'CV'
        WHEN 'dars' THEN 'DARS'
        WHEN 'data' THEN 'Data'
        WHEN 'data review' THEN 'Data Review'
        WHEN 'data reviewed' THEN 'Data Reviewed'
        WHEN 'data summary' THEN 'Data Summary'
        WHEN 'date and results of last a1c' THEN 'Date and Results of Last A1C'
        WHEN 'date of last visit' THEN 'Date of Last Visit'
        WHEN 'decadron' THEN 'Decadron'
        WHEN 'decision making' THEN 'Decision Making'
        WHEN 'deep tendon reflexes' THEN 'Deep Tendon Reflexes'
        WHEN 'deep tendon reflexes of the upper and lower extremities' THEN 'Deep Tendon Reflexes of the Upper and Lower Extremities'
        WHEN 'deep tendon reflexes upper and lower extremities' THEN 'Deep Tendon Reflexes of the Upper and Lower Extremities'
        WHEN 'degenerative' THEN 'Degenerative'
        WHEN 'delayed recall' THEN 'Delayed Recall'
        WHEN 'dementia: cognition' THEN 'Dementia: Cognition'
        WHEN 'dementia: cognition assessment tool used' THEN 'Dementia: Cognition Assessment Tool Used'
        WHEN 'dental exam' THEN 'Dental Exam'
        WHEN 'depacon' THEN 'Depacon'
        WHEN 'depressed or irritable mood, frequent crying' THEN 'Depressed or Irritable Mood, Frequent Crying'
        WHEN 'depression screening' THEN 'Depression Screening'
        WHEN 'depressive symptoms' THEN 'Depressive Symptoms'
        WHEN 'dermatomal reflexes' THEN 'Dermatomal Reflexes'
        WHEN 'description' THEN 'Description'
        WHEN 'desired body weight' THEN 'Desired Body Weight'
        WHEN 'details related to falls' THEN 'Details Related to Falls'
        WHEN 'development' THEN 'Development'
        WHEN 'dhi' THEN 'DHI'
        WHEN 'diabetes' THEN 'Diabetes'
        WHEN 'diabetes eye exam' THEN 'Diabetes Eye Exam'
        WHEN 'diabetes foot exam' THEN 'Diabetes Foot Exam'
        WHEN 'diabetic foot exam' THEN 'Diabetic Foot Exam'
        WHEN 'diagnosis' THEN 'Diagnosis'
        WHEN 'diagnostic' THEN 'Diagnostic Testing'
        WHEN 'diagnostic testing' THEN 'Diagnostic Testing'
        WHEN 'diagnostic tests reviewed' THEN 'Diagnostic Tests Reviewed'
        WHEN 'diagnostics' THEN 'Diagnostics'
        WHEN 'diet history' THEN 'Diet History'
        WHEN 'difficulty in swallowing' THEN 'Difficulty in Swallowing'
        WHEN 'difficulty initiating sleep' THEN 'Difficulty Initiating Sleep'
        WHEN 'difficulty staying asleep' THEN 'Difficulty Staying Asleep'
        WHEN 'diminished concentration' THEN 'Diminished Concentration'
        WHEN 'disability / ssd / ssi' THEN 'Disability / SSD / SSI'
        WHEN 'disorientation' THEN 'Disorientation'
        WHEN 'distance that the patient can ambulate without stopping while utilizing an assistive device' THEN 'Distance That the Patient Can Ambulate Without Stopping While Utilizing an Assistive Device'
        WHEN 'distress' THEN 'Distress'
        WHEN 'dme / cmn' THEN 'DME / CMN'
        WHEN 'drawer test' THEN 'Drawer Test'
        WHEN 'dtr' THEN 'DTRs'
        WHEN 'dtrs' THEN 'DTRs'
        WHEN 'e/m counseling' THEN 'E/M Counseling'
        WHEN 'ear' THEN 'Ears'
        WHEN 'ears' THEN 'Ears'
        WHEN 'ears, nose, throat' THEN 'Ears, Nose, Throat'
        WHEN 'echocardiogram' THEN 'Echocardiogram'
        WHEN 'edss' THEN 'EDSS'
        WHEN 'edss score' THEN 'EDSS Score'
        WHEN 'education' THEN 'Education'
        WHEN 'eeg' THEN 'EEG'
        WHEN 'elbow' THEN 'Elbow'
        WHEN 'emg' THEN 'EMG'
        WHEN 'endocrine labs reviewed' THEN 'Endocrine Labs Reviewed'
        WHEN 'endurance' THEN 'Endurance'
        WHEN 'energy needs' THEN 'Energy Needs'
        WHEN 'enmt' THEN 'ENMT'
        WHEN 'ent' THEN 'ENT'
        WHEN 'eoms' THEN 'EOMS'
        WHEN 'eversion stress' THEN 'Eversion Stress'
        WHEN 'exam' THEN 'Examination'
        WHEN 'examination' THEN 'Examination'
        WHEN 'examination of carotid arteries (pulse amplitudes, bruits)' THEN 'Examination of Carotid Arteries (Pulse Amplitudes, Bruits)'
        WHEN 'examination of coordination' THEN 'Examination of Coordination'
        WHEN 'examination of deep tendon reflexes in upper and lower' THEN 'Examination of Deep Tendon Reflexes in Upper and Lower'
        WHEN 'examination of gait and station' THEN 'Examination of Gait and Station'
        WHEN 'examination of peripheral vascular systems' THEN 'Examination of Peripheral Vascular Systems'
        WHEN 'examination of sensation' THEN 'Examination of Sensation'
        WHEN 'exercise' THEN 'Exercise'
        WHEN 'expanded disability status scale' THEN 'Expanded Disability Status Scale'
        WHEN 'expanded disability status scale (edss)' THEN 'Expanded Disability Status Scale (EDSS)'
        WHEN 'extension' THEN 'Extension'
        WHEN 'external genitalia' THEN 'External Genitalia'
        WHEN 'external genitals' THEN 'External Genitalia'
        WHEN 'extremeties' THEN 'Extremeties'
        WHEN 'extremeties examination' THEN 'Extremeties Examination'
        WHEN 'extremities' THEN 'Extremities'
        WHEN 'extremities/back' THEN 'Extremities and Back'
        WHEN 'extremities: skin, vascular' THEN 'Extremities: Skin, Vascular'
        WHEN 'eye' THEN 'Eyes'
        WHEN 'eye contact' THEN 'Eye Contact'
        WHEN 'eye exam' THEN 'Eye Exam'
        WHEN 'eye movement' THEN 'Eye Movement'
        WHEN 'eyelids' THEN 'Eyelids'
        WHEN 'eyes' THEN 'Eyes'
        WHEN 'face' THEN 'Face'
        WHEN 'facial' THEN 'Facial Exam'
        WHEN 'facial exam' THEN 'Facial Exam'
        WHEN 'facial expression' THEN 'Facial Expression'
        WHEN 'facial power' THEN 'Facial Power'
        WHEN 'facial sensation' THEN 'Facial Sensation'
        WHEN 'fall-balance-mobility' THEN 'Fall-Balance-Mobility'
        WHEN 'fatigue/loss of energy' THEN 'Fatigue/Loss of Energy'
        WHEN 'fatigue/weakness' THEN 'Fatigue/Weakness'
        WHEN 'feelings of worthlessness/guilt' THEN 'Feelings of Worthlessness/Guilt'
        WHEN 'feet' THEN 'Feet'
        WHEN 'female development' THEN 'Female Development'
        WHEN 'female genitourinary' THEN 'Female Genitourinary'
        WHEN 'finger jerks' THEN 'Finger Jerks'
        WHEN 'finger tap-left' THEN 'Finger Tap-Left'
        WHEN 'finger tap-right' THEN 'Finger Tap-Right'
        WHEN 'finkelstein''s test' THEN 'Finkelstein''s Test'
        WHEN 'fist' THEN 'Fist'
        WHEN 'flexion' THEN 'Flexion'
        WHEN 'flexion/extension' THEN 'Flexion/Extension'
        WHEN 'fluid needs' THEN 'Fluid Needs'
        WHEN 'follow a 3-stage command score' THEN 'Follow a 3-Stage Command Score'
        WHEN 'follow-up cognitive assessment' THEN 'Follow-Up Cognitive Assessment'
        WHEN 'food allergies/intolerances/preferences' THEN 'Food Allergies/Intolerances/Preferences'
        WHEN 'foot exam' THEN 'Foot Exam'
        WHEN 'frenchay dysarthria assessment- 2 (fda-2)' THEN 'Frenchay Dysarthria Assessment- 2 (FDA-2)'
        WHEN 'frequency of symptoms' THEN 'Frequency of Symptoms'
        WHEN 'frequency/duration' THEN 'Frequency/Duration'
        WHEN 'fund of knowledge' THEN 'Fund of Knowledge'
        WHEN 'fund of knowledge (awareness of current events)' THEN 'Fund of Knowledge (Awareness of Current Events)'
        WHEN 'fundi' THEN 'Fundi'
        WHEN 'fundoscopy' THEN 'Funduscopic Exam'
        WHEN 'funduscopic exam' THEN 'Funduscopic Exam'
        WHEN 'gait' THEN 'Gait'
        WHEN 'gait and stance' THEN 'Gait and Stance'
        WHEN 'gait and station' THEN 'Gait and Station'
        WHEN 'gait examination' THEN 'Gait Examination'
        WHEN 'gait is' THEN 'Gait'
        WHEN 'gait/ balance' THEN 'Gait/ Balance'
        WHEN 'gait/posture' THEN 'Gait/Posture'
        WHEN 'gait/stance' THEN 'Gait/Stance'
        WHEN 'gastrointestinal' THEN 'Gastrointestinal'
        WHEN 'general' THEN 'General Examination'
        WHEN 'general appearance' THEN 'General Appearance'
        WHEN 'general appearance and alertness' THEN 'General Appearance and Alertness'
        WHEN 'general appearances' THEN 'General Appearances'
        WHEN 'general exam' THEN 'General Examination'
        WHEN 'general/constitutional' THEN 'General and Constitutional'
        WHEN 'genitalia' THEN 'Genitalia'
        WHEN 'genitourinary/bowel' THEN 'Genitourinary/Bowel'
        WHEN 'gi symptoms' THEN 'GI Symptoms'
        WHEN 'glossopharyngeal' THEN 'Glossopharyngeal'
        WHEN 'glucose' THEN 'Glucose'
        WHEN 'goal' THEN 'Goal'
        WHEN 'grooming' THEN 'Grooming'
        WHEN 'guaiac' THEN 'Guaiac'
        WHEN 'hall-pike test' THEN 'Hall-Pike Test'
        WHEN 'hallpike maneuver' THEN 'Hallpike Maneuver'
        WHEN 'hallucinations/delusions' THEN 'Hallucinations/Delusions'
        WHEN 'hand' THEN 'Hand'
        WHEN 'hand grips-left' THEN 'Hand Grips-Left'
        WHEN 'hand grips-right' THEN 'Hand Grips-Right'
        WHEN 'hands' THEN 'Hands'
        WHEN 'hawkins' THEN 'Hawkins'
        WHEN 'head' THEN 'Head'
        WHEN 'head & neck' THEN 'Head & Neck'
        WHEN 'head and face' THEN 'Head and Face'
        WHEN 'head and neck muscle examination' THEN 'Head and Neck Muscle Examination'
        WHEN 'head structured' THEN 'Head Structured'
        WHEN 'head, eyes, ears, nose, throat' THEN 'Head, Eyes, Ears, Nose, Throat'
        WHEN 'headaches' THEN 'Headaches'
        WHEN 'hearing' THEN 'Hearing'
        WHEN 'hearing device selection' THEN 'Hearing Device Selection'
        WHEN 'heart' THEN 'Heart'
        WHEN 'heart / vascular' THEN 'Heart / Vascular'
        WHEN 'heart/cardiac' THEN 'Heart and Cardiac'
        WHEN 'heating pad to iv site' THEN 'Heating Pad to IV Site'
        WHEN 'heent' THEN 'HEENT'
        WHEN 'hematological' THEN 'Hematological'
        WHEN 'higher cognitive functions' THEN 'Higher Cognitive Functions'
        WHEN 'higher cortical function' THEN 'Higher Cortical Function'
        WHEN 'higher integrative functions' THEN 'Higher Integrative Functions'
        WHEN 'hip' THEN 'Hip'
        WHEN 'hip-knee-ankle' THEN 'Hip-Knee-Ankle'
        WHEN 'hips' THEN 'Hips'
        WHEN 'historic diagnostic testing' THEN 'Historic Diagnostic Testing'
        WHEN 'history of depression, substance abuse' THEN 'History of Depression, Substance Abuse'
        WHEN 'hoffman signs' THEN 'Hoffman Signs'
        WHEN 'holter monitor' THEN 'Holter Monitor'
        WHEN 'home safety eval/ driving safety eval' THEN 'Home Safety Eval/ Driving Safety Eval'
        WHEN 'homicidal ideations' THEN 'Homicidal Ideations'
        WHEN 'hypertrophy' THEN 'Hypertrophy'
        WHEN 'hypoglossal' THEN 'Hypoglossal'
        WHEN 'i' THEN 'Cranial Nerve I'
        WHEN 'ibw' THEN 'IBW'
        WHEN 'ii' THEN 'Cranial Nerve II'
        WHEN 'iii, iv' THEN 'Cranial Nerve III and IV'
        WHEN 'iii, iv, and vi' THEN 'Cranial Nerve III, IV, and VI'
        WHEN 'iii, iv, vi' THEN 'Cranial Nerve III, IV, and VI'
        WHEN 'imaging personally reviewed' THEN 'Imaging Personally Reviewed'
        WHEN 'imaging reviewed' THEN 'Imaging Reviewed'
        WHEN 'impressions' THEN 'Impressions'
        WHEN 'in a car, while stopped for a few minutes in traffic' THEN 'In a Car, While Stopped for a Few Minutes in Traffic'
        WHEN 'incision' THEN 'Incision'
        WHEN 'independent interpretation' THEN 'Independent Interpretation'
        WHEN 'infusion pump -baxter 6201' THEN 'Infusion Pump -Baxter 6201'
        WHEN 'infusion rate' THEN 'Infusion Rate'
        WHEN 'initials' THEN 'Initials'
        WHEN 'insight' THEN 'Insight'
        WHEN 'insight/judgement' THEN 'Insight/Judgement'
        WHEN 'inspection' THEN 'Inspection'
        WHEN 'inspection/palpation' THEN 'Inspection and Palpation'
        WHEN 'integumentary' THEN 'Integumentary'
        WHEN 'intellect' THEN 'Intellect'
        WHEN 'intellectual' THEN 'Intellectual'
        WHEN 'intelligible speech, familiar listener' THEN 'Intelligible Speech, Familiar Listener'
        WHEN 'intelligible speech, unfamiliar listener' THEN 'Intelligible Speech, Unfamiliar Listener'
        WHEN 'intensity' THEN 'Intensity'
        WHEN 'interpretation' THEN 'Interpretation'
        WHEN 'interpretation of tests' THEN 'Interpretation of Tests'
        WHEN 'inversion stress' THEN 'Inversion Stress'
        WHEN 'involuntary movement' THEN 'Involuntary Movements'
        WHEN 'involuntary movements' THEN 'Involuntary Movements'
        WHEN 'items' THEN 'Items'
        WHEN 'ivig' THEN 'IVIG'
        WHEN 'ix' THEN 'Cranial Nerve IX'
        WHEN 'ix, x' THEN 'Cranial Nerve IX and X'
        WHEN 'jaw exam' THEN 'Jaw Exam'
        WHEN 'joints' THEN 'Joints'
        WHEN 'judgment' THEN 'Judgment'
        WHEN 'juice' THEN 'Juice'
        WHEN 'ketones' THEN 'Ketones'
        WHEN 'kidney problems' THEN 'Kidney Problems'
        WHEN 'knee' THEN 'Knee'
        WHEN 'knees' THEN 'Knees'
        WHEN 'knowledge and mood' THEN 'Knowledge and Mood'
        WHEN 'known triggers' THEN 'Known Triggers'
        WHEN 'kyphosis' THEN 'Kyphosis'
        WHEN 'lab tests reviewed' THEN 'Lab Tests Reviewed'
        WHEN 'lab work' THEN 'Lab Work'
        WHEN 'lab/imaging' THEN 'Labs/Imaging'
        WHEN 'laboratory' THEN 'Laboratory'
        WHEN 'labs' THEN 'Laboratory'
        WHEN 'labs reviewed' THEN 'Labs Reviewed'
        WHEN 'labs/imaging' THEN 'Labs/Imaging'
        WHEN 'language' THEN 'Language'
        WHEN 'le mmt' THEN 'LE MMT'
        WHEN 'le rom' THEN 'LE ROM'
        WHEN 'le sensation' THEN 'LE Sensation'
        WHEN 'left lower extremity joint(s)' THEN 'Left Lower Extremity Joint(s)'
        WHEN 'left side' THEN 'Left Side'
        WHEN 'left upper extremity joint(s)' THEN 'Left Upper Extremity Joint(s)'
        WHEN 'leg agility-left' THEN 'Leg Agility-Left'
        WHEN 'leg agility-right' THEN 'Leg Agility-Right'
        WHEN 'legs' THEN 'Legs'
        WHEN 'leukocyte esterace' THEN 'Leukocyte Esterace'
        WHEN 'level of arousal' THEN 'Level of Arousal'
        WHEN 'level of consciousness' THEN 'Level of Consciousness'
        WHEN 'lf pta' THEN 'LF PTA'
        WHEN 'light touch' THEN 'Light Touch'
        WHEN 'lmp' THEN 'LMP'
        WHEN 'location' THEN 'Location'
        WHEN 'long term memory' THEN 'Long Term Memory'
        WHEN 'low contrast visual letter acuity test (lcla)' THEN 'Low Contrast Visual Letter Acuity Test (LCLA)'
        WHEN 'low-back exam' THEN 'Lower Back Exam'
        WHEN 'lower back' THEN 'Lower Back Exam'
        WHEN 'lower extremities' THEN 'Lower Extremities'
        WHEN 'lower leg' THEN 'Lower Leg'
        WHEN 'lumbar' THEN 'Lumbar'
        WHEN 'lumbar spine' THEN 'Lumbar Spine'
        WHEN 'lumbar spine corrupt' THEN 'Lumbar Spine Corrupt'
        WHEN 'lumbar spine exam' THEN 'Lumbar Spine Exam'
        WHEN 'lung exam' THEN 'Lung Exam'
        WHEN 'lungs' THEN 'Lungs'
        WHEN 'lying down to rest in the afternoon' THEN 'Lying Down to Rest in the Afternoon'
        WHEN 'lymph node examination' THEN 'Lymph Node Examination'
        WHEN 'lymph nodes' THEN 'Lymph Nodes'
        WHEN 'lymphatic' THEN 'Lymphatic'
        WHEN 'lymphatics' THEN 'Lymphatics'
        WHEN 'ma to complete' THEN 'Ma to Complete'
        WHEN 'magnet' THEN 'Magnet'
        WHEN 'male female genitourinary' THEN 'Male Female Genitourinary'
        WHEN 'male genitalia' THEN 'Male Genitalia'
        WHEN 'male genitourinary' THEN 'Male Genitourinary'
        WHEN 'manual muscle testing' THEN 'Manual Muscle Testing'
        WHEN 'manufacturer' THEN 'Manufacturer'
        WHEN 'mcmurray' THEN 'McMurray'
        WHEN 'mcp and ip joints' THEN 'MCP and IP Joints'
        WHEN 'mechanical signs' THEN 'Mechanical Signs'
        WHEN 'medical records' THEN 'Medical Records'
        WHEN 'medication assistance' THEN 'Medication Assistance'
        WHEN 'medications and supplements' THEN 'Medications and Supplements'
        WHEN 'medications reviewed' THEN 'Medications Reviewed'
        WHEN 'memory' THEN 'Memory'
        WHEN 'memory problems' THEN 'Memory Problems'
        WHEN 'mental status' THEN 'Mental Status Examination'
        WHEN 'mental status exam' THEN 'Mental Status Examination'
        WHEN 'mental status examination' THEN 'Mental Status Examination'
        WHEN 'middle ears' THEN 'Middle Ears'
        WHEN 'mini-mental state score' THEN 'Mini-Mental State Examination'
        WHEN 'misc' THEN 'Misc'
        WHEN 'miscellaneous' THEN 'Miscellaneous'
        WHEN 'mmse' THEN 'Mini-Mental State Examination'
        WHEN 'mmse score' THEN 'Mini-Mental State Examination'
        WHEN 'moca score' THEN 'MoCA Score'
        WHEN 'modality time' THEN 'Modality Time'
        WHEN 'model' THEN 'Model'
        WHEN 'modified fatigue impact scale (mfis)' THEN 'Modified Fatigue Impact Scale (MFIS)'
        WHEN 'montreal cognitive assessment (moca)' THEN 'Montreal Cognitive Assessment (MoCA)'
        WHEN 'mood' THEN 'Mood'
        WHEN 'mood and affect' THEN 'Mood and Affect'
        WHEN 'mood/affect' THEN 'Mood and Affect'
        WHEN 'more' THEN 'More'
        WHEN 'motility' THEN 'Motility'
        WHEN 'motor' THEN 'Motor'
        WHEN 'motor / coordination exam' THEN 'Motor and Coordination Exam'
        WHEN 'motor bulk' THEN 'Motor Bulk'
        WHEN 'motor control' THEN 'Motor Control'
        WHEN 'motor exam' THEN 'Motor Examination'
        WHEN 'motor examination' THEN 'Motor Examination'
        WHEN 'motor power' THEN 'Motor Power'
        WHEN 'motor strength' THEN 'Motor Strength'
        WHEN 'motor system' THEN 'Motor System'
        WHEN 'motor tone' THEN 'Motor Tone'
        WHEN 'motor/musculoskeletal' THEN 'Motor and Musculoskeletal'
        WHEN 'motor/sensory/reflex/balance examination' THEN 'Motor/Sensory/Reflex/Balance Examination'
        WHEN 'mouth' THEN 'Mouth'
        WHEN 'mouth/throat' THEN 'Mouth and Throat'
        WHEN 'movement' THEN 'Movements'
        WHEN 'movements' THEN 'Movements'
        WHEN 'mra' THEN 'MRA'
        WHEN 'mri' THEN 'MRI'
        WHEN 'mri report' THEN 'MRI Report'
        WHEN 'mri/imaging' THEN 'MRI/Imaging'
        WHEN 'mris' THEN 'MRIs'
        WHEN 'ms' THEN 'MS'
        WHEN 'msk' THEN 'MSK'
        WHEN 'muscle bulk' THEN 'Muscle Bulk'
        WHEN 'muscle exam' THEN 'Muscle Exam'
        WHEN 'muscle strength' THEN 'Muscle Strength'
        WHEN 'muscle strength and tone' THEN 'Muscle Strength and Tone'
        WHEN 'muscle strength/tone in upper/lower extremities' THEN 'Muscle Strength and Tone in Upper and Lower Extremities'
        WHEN 'muscle tone' THEN 'Muscle Tone'
        WHEN 'muscle tone and bulk' THEN 'Muscle Tone and Bulk'
        WHEN 'muscle tone in upper and lower extremities' THEN 'Muscle Tone in Upper and Lower Extremities'
        WHEN 'musculoskeletal' THEN 'Musculoskeletal Examination'
        WHEN 'musculoskeletal examination' THEN 'Musculoskeletal Examination'
        WHEN 'musculoskeletal structured' THEN 'Musculoskeletal Structured'
        WHEN 'musculoskeletal system' THEN 'Musculoskeletal System'
        WHEN 'musculoskeletal/extremities' THEN 'Musculoskeletal and Extremities'
        WHEN 'myofascial trigger points' THEN 'Myofascial Trigger Points'
        WHEN 'n/v/d/c' THEN 'N/V/D/C'
        WHEN 'nad' THEN 'NAD'
        WHEN 'name a pencil and watch score' THEN 'Name a Pencil and Watch Score'
        WHEN 'name all 3 objects trials' THEN 'Name All 3 Objects Trials'
        WHEN 'naming' THEN 'Naming'
        WHEN 'nare' THEN 'NARE'
        WHEN 'ncv' THEN 'NCV'
        WHEN 'neck' THEN 'Neck'
        WHEN 'neck and back' THEN 'Neck and Back'
        WHEN 'neck exam' THEN 'Neck Exam'
        WHEN 'neck, thyroid' THEN 'Neck and Thyroid'
        WHEN 'neck/thyroid' THEN 'Neck and Thyroid'
        WHEN 'needle type/size' THEN 'Needle Type/Size'
        WHEN 'neers' THEN 'Neers'
        WHEN 'neoplasms' THEN 'Neoplasms'
        WHEN 'neuro' THEN 'Neuro'
        WHEN 'neuro/psych/balance' THEN 'Neuro/Psych/Balance'
        WHEN 'neurobehavioral exam' THEN 'Neurobehavioral Exam'
        WHEN 'neurobehavioral status exam' THEN 'Neurobehavioral Status Exam'
        WHEN 'neurologic' THEN 'Neurological Examination'
        WHEN 'neurologic / musculoskeletal - lowers and general' THEN 'Neurologic / Musculoskeletal - Lowers and General'
        WHEN 'neurologic exam' THEN 'Neurological Examination'
        WHEN 'neurological' THEN 'Neurological Examination'
        WHEN 'neurological exam' THEN 'Neurological Examination'
        WHEN 'neurological examination' THEN 'Neurological Examination'
        WHEN 'neurological system' THEN 'Neurological System'
        WHEN 'neurological-cognitive' THEN 'Neurological and Cognitive Exam'
        WHEN 'neurophysiology' THEN 'Neurophysiology'
        WHEN 'neuropsychiatric' THEN 'Neuropsychiatric'
        WHEN 'neuropsychiatric inventory' THEN 'Neuropsychiatric Inventory'
        WHEN 'neuropsychiatric testing' THEN 'Neuropsychiatric Testing'
        WHEN 'neuropsychologic testing' THEN 'Neuropsychologic Testing'
        WHEN 'neuropsychology' THEN 'Neuropsychology'
        WHEN 'neurovascular exam' THEN 'Neurovascular Exam'
        WHEN 'nitrite' THEN 'Nitrite'
        WHEN 'no' THEN 'No'
        WHEN 'nose' THEN 'Nose'
        WHEN 'ns flush' THEN 'NS Flush'
        WHEN 'ns flush/heparin flush' THEN 'NS Flush/Heparin Flush'
        WHEN 'ns hydration before and after ivig' THEN 'NS Hydration Before and After IVIG'
        WHEN 'nursing notes' THEN 'Nursing Notes'
        WHEN 'nutrition diagnosis' THEN 'Nutrition Diagnosis'
        WHEN 'nutrition risk' THEN 'Nutrition Risk'
        WHEN 'obtained history from someone other than patient' THEN 'Obtained History from Someone Other Than Patient'
        WHEN 'occipital nerve' THEN 'Occipital Nerve'
        WHEN 'ocular' THEN 'Ocular'
        WHEN 'oculomotor' THEN 'Oculomotor Exam'
        WHEN 'oculomotor tests' THEN 'Oculomotor Exam'
        WHEN 'olfactory' THEN 'Olfactory'
        WHEN 'ophthalmic examination shows' THEN 'Ophthalmic Examination Shows'
        WHEN 'ophthalmologic' THEN 'Ophthalmoscopic Exam'
        WHEN 'ophthalmoscopic exam' THEN 'Ophthalmoscopic Exam'
        WHEN 'optic' THEN 'Optic'
        WHEN 'oral cavity' THEN 'Oral Cavity'
        WHEN 'oral cavity/throat' THEN 'Oral Cavity and Throat'
        WHEN 'oral phase observations' THEN 'Oral Phase Observations'
        WHEN 'orientation' THEN 'Orientation'
        WHEN 'orientation to time, place and person' THEN 'Orientation to Time, Place and Person'
        WHEN 'orientation-time/place/person' THEN 'Orientation-Time/Place/Person'
        WHEN 'oriented' THEN 'Oriented'
        WHEN 'oropharynx' THEN 'Oropharynx'
        WHEN 'other' THEN 'Other'
        WHEN 'other data' THEN 'Other Data'
        WHEN 'other medical hx' THEN 'Other Medical Hx'
        WHEN 'other pathologic reflexes are' THEN 'Other Pathologic Reflexes Are'
        WHEN 'others' THEN 'Others'
        WHEN 'otoscopy' THEN 'Otoscopy'
        WHEN 'outcome' THEN 'Outcome'
        WHEN 'outside records' THEN 'Outside Records'
        WHEN 'ovaries' THEN 'Ovaries'
        WHEN 'over the last 2 weeks, how often have you been bothered by' THEN 'Over the Last 2 Weeks, How Often Have You Been Bothered by'
        WHEN 'pac' THEN 'PAC'
        WHEN 'pace of ambulation' THEN 'Pace of Ambulation'
        WHEN 'pacs imaging' THEN 'PACS Imaging'
        WHEN 'pain' THEN 'Pain'
        WHEN 'pain scale' THEN 'Pain Scale'
        WHEN 'pain/spasms' THEN 'Pain/Spasms'
        WHEN 'palate elevation' THEN 'Palate Elevation'
        WHEN 'palpation' THEN 'Palpation'
        WHEN 'pap smear' THEN 'Pap Smear'
        WHEN 'paraspinal muscle spasm' THEN 'Paraspinal Muscle Spasm'
        WHEN 'patellofemoral joint' THEN 'Patellofemoral Joint'
        WHEN 'patency of ns lock' THEN 'Patency of NS Lock'
        WHEN 'pathology' THEN 'Pathology'
        WHEN 'patient can physically operate the tiller (scooter) or joystick (power wheelchair)' THEN 'Patient Can Physically Operate the Tiller (Scooter) or Joystick (Power Wheelchair)'
        WHEN 'patient can safely transfer to/from device' THEN 'Patient Can Safely Transfer to/from Device'
        WHEN 'patient education' THEN 'Patient Education'
        WHEN 'patient family goals' THEN 'Patient Family Goals'
        WHEN 'patient has the mental capability to operate a powered device' THEN 'Patient Has the Mental Capability to Operate a Powered Device'
        WHEN 'patient response to treatment' THEN 'Patient Response to Treatment'
        WHEN 'patient tolerance' THEN 'Patient Tolerance'
        WHEN 'patient-stated food "weaknesses"' THEN 'Patient-Stated Food "Weaknesses"'
        WHEN 'perceptual motor' THEN 'Perceptual Motor'
        WHEN 'performed' THEN 'Performed'
        WHEN 'peripheral edema' THEN 'Peripheral Edema'
        WHEN 'peripheral neurologic examination' THEN 'Peripheral Neurologic Examination'
        WHEN 'peripheral pulses' THEN 'Peripheral Pulses'
        WHEN 'peripheral vascular system' THEN 'Peripheral Vascular System'
        WHEN 'ph' THEN 'PH'
        WHEN 'phalen''s sign' THEN 'Phalen''s Sign'
        WHEN 'pharyngeal phase observations & symptoms' THEN 'Pharyngeal Phase Observations & Symptoms'
        WHEN 'physical exam' THEN 'Physical Exam'
        WHEN 'physical findings' THEN 'Physical Findings'
        WHEN 'pinprick, light touch, vibration and position' THEN 'Pinprick, Light Touch, Vibration and Position'
        WHEN 'pitch' THEN 'Pitch'
        WHEN 'plan' THEN 'Plan'
        WHEN 'plantar reflexes' THEN 'Plantar Reflexes'
        WHEN 'plantar response' THEN 'Plantar Responses'
        WHEN 'plantar responses' THEN 'Plantar Responses'
        WHEN 'plantars' THEN 'Plantars'
        WHEN 'plantars are' THEN 'Plantars'
        WHEN 'podiatric' THEN 'Podiatric'
        WHEN 'positional tests' THEN 'Positional Tests'
        WHEN 'postural exam' THEN 'Postural Exam'
        WHEN 'postural instability' THEN 'Postural Instability'
        WHEN 'posture' THEN 'Posture'
        WHEN 'potential gastroesophageal symptoms' THEN 'Potential Gastroesophageal Symptoms'
        WHEN 'power' THEN 'Power'
        WHEN 'pragmatics' THEN 'Pragmatics'
        WHEN 'present for evaluation' THEN 'Present for Evaluation'
        WHEN 'presidents' THEN 'Presidents'
        WHEN 'previous therapy relating to the presenting problem' THEN 'Previous Therapy Relating to the Presenting Problem'
        WHEN 'primary speech characteristics' THEN 'Primary Speech Characteristics'
        WHEN 'problems chewing or swallowing' THEN 'Problems Chewing or Swallowing'
        WHEN 'progress toward goal' THEN 'Progress Toward Goal'
        WHEN 'progression of ambulation difficulty over time' THEN 'Progression of Ambulation Difficulty Over Time'
        WHEN 'prolongation of /a/' THEN 'Prolongation of /a/'
        WHEN 'pron/sup-left' THEN 'Pron/Sup-Left'
        WHEN 'pron/sup-right' THEN 'Pron/Sup-Right'
        WHEN 'pronator drift' THEN 'Pronator Drift'
        WHEN 'proprioception' THEN 'Proprioception'
        WHEN 'prosody: rate, length of utterance' THEN 'Prosody: Rate, Length of Utterance'
        WHEN 'protein' THEN 'Protein'
        WHEN 'protein needs' THEN 'Protein Needs'
        WHEN 'psych' THEN 'Psych'
        WHEN 'psychiatric' THEN 'Psychiatric'
        WHEN 'psychological' THEN 'Psychological'
        WHEN 'psychomotor slowing/agitation' THEN 'Psychomotor Slowing/Agitation'
        WHEN 'psychosis (ie delusional/paranoid thoughts, hallucinations)' THEN 'Psychosis (ie Delusional/Paranoid Thoughts, Hallucinations)'
        WHEN 'pulmonary examination' THEN 'Pulmonary Examination'
        WHEN 'pulse' THEN 'Pulses'
        WHEN 'pulses' THEN 'Pulses'
        WHEN 'pyramidal functions' THEN 'Pyramidal Functions'
        WHEN 'radiology' THEN 'Radiology'
        WHEN 'range of motion' THEN 'Range of Motion'
        WHEN 'range of motion of neck' THEN 'Range of Motion of Neck'
        WHEN 'range of motion of spines' THEN 'Range of Motion of Spines'
        WHEN 'read and obey "close your eyes" score' THEN 'Read and Obey "Close Your Eyes" Score'
        WHEN 'reading comprehension' THEN 'Reading Comprehension'
        WHEN 'reason for referral' THEN 'Reason for Referral'
        WHEN 'reason(s) for inability to use a manual wheelchair' THEN 'Reason(s) for Inability to Use a Manual Wheelchair'
        WHEN 'reason(s) patient requires a power mobility device' THEN 'Reason(s) Patient Requires a Power Mobility Device'
        WHEN 'reason(s) patient requires a power wheelchair' THEN 'Reason(s) Patient Requires a Power Wheelchair'
        WHEN 'recall' THEN 'Recalls'
        WHEN 'recalls' THEN 'Recalls'
        WHEN 'recent and remote memory' THEN 'Recent and Remote Memory'
        WHEN 'recent losses or crises, change in physical health status' THEN 'Recent Losses or Crises, Change in Physical Health Status'
        WHEN 'recent memory' THEN 'Recent Memory'
        WHEN 'reclast' THEN 'Reclast'
        WHEN 'reclast education' THEN 'Reclast Education'
        WHEN 'recommendations' THEN 'Recommendations'
        WHEN 'recommendations - medical' THEN 'Recommendations - Medical'
        WHEN 'recommendations - procedures' THEN 'Recommendations - Procedures'
        WHEN 'recommendations - testing' THEN 'Recommendations - Testing'
        WHEN 'records from pcp/referring provider' THEN 'Records from PCP/Referring Provider'
        WHEN 'records requested' THEN 'Records Requested'
        WHEN 'records reviewed' THEN 'Records Reviewed'
        WHEN 'rectal' THEN 'Rectal Exam'
        WHEN 'rectal exam' THEN 'Rectal Exam'
        WHEN 'rectum' THEN 'Rectum'
        WHEN 'referring physician' THEN 'Referring Physicians'
        WHEN 'referring physicians' THEN 'Referring Physicians'
        WHEN 'reflex examination' THEN 'Reflex Examination'
        WHEN 'reflexes' THEN 'Reflexes'
        WHEN 'refraction' THEN 'Refraction'
        WHEN 'registration' THEN 'Registration'
        WHEN 'reglan' THEN 'Reglan'
        WHEN 'rehab potential' THEN 'Rehab Potential'
        WHEN 'rehabilitation inpatient / outpatient' THEN 'Rehabilitation Inpatient / Outpatient'
        WHEN 'repeat the following, "no ifs, ands, or buts" score' THEN 'Repeat the Following, "No Ifs, Ands, or Buts" Score'
        WHEN 'repitition' THEN 'Repitition'
        WHEN 'reports' THEN 'Reports'
        WHEN 'requested records from patient pcp' THEN 'Requested Records from Patient PCP'
        WHEN 'requested records from pcp/referring provider' THEN 'Requested Records from PCP/Referring Provider'
        WHEN 'respiratory' THEN 'Respiratory'
        WHEN 'respiratory status' THEN 'Respiratory Status'
        WHEN 'respiratory support' THEN 'Respiratory Support'
        WHEN 'respiratory system' THEN 'Respiratory System'
        WHEN 'response to treatment' THEN 'Response to Treatment'
        WHEN 'rest tremor-left hand' THEN 'Rest Tremor-Left Hand'
        WHEN 'rest tremor-left leg' THEN 'Rest Tremor-Left Leg'
        WHEN 'rest tremor-right hand' THEN 'Rest Tremor-Right Hand'
        WHEN 'rest tremor-right leg' THEN 'Rest Tremor-Right Leg'
        WHEN 'restart' THEN 'Restart'
        WHEN 'restless legs' THEN 'Restless Legs'
        WHEN 'results' THEN 'Results'
        WHEN 'review of clinical lab tests' THEN 'Review of Clinical Lab Tests'
        WHEN 'review of medical diagnostic test' THEN 'Review of Medical Diagnostic Test'
        WHEN 'review of old records' THEN 'Review of Old Records'
        WHEN 'review of radiology tests' THEN 'Review of Radiology Tests'
        WHEN 'reviewed' THEN 'Reviewed'
        WHEN 'rib tenderness' THEN 'Rib Tenderness'
        WHEN 'right lower extremity joint(s)' THEN 'Right Lower Extremity Joint(s)'
        WHEN 'right side' THEN 'Right Side'
        WHEN 'right upper extremity joint(s)' THEN 'Right Upper Extremity Joint(s)'
        WHEN 'rigidity-lle' THEN 'Rigidity-LLE'
        WHEN 'rigidity-lue' THEN 'Rigidity-LUE'
        WHEN 'rigidity-neck' THEN 'Rigidity-Neck'
        WHEN 'rigidity-rle' THEN 'Rigidity-RLE'
        WHEN 'rigidity-rue' THEN 'Rigidity-RUE'
        WHEN 'risk factors' THEN 'Risk Factors'
        WHEN 'rituxan' THEN 'Rituxan'
        WHEN 'romberg' THEN 'Romberg'
        WHEN 'romberg examination' THEN 'Romberg Examination'
        WHEN 'romberg test' THEN 'Romberg Test'
        WHEN 'romberg''s' THEN 'Romberg'
        WHEN 'sacral sensory is' THEN 'Sacral Sensory Is'
        WHEN 'sacrum' THEN 'Sacrum'
        WHEN 'scale' THEN 'Scale'
        WHEN 'scalp' THEN 'Scalp'
        WHEN 'sclera' THEN 'Sclera'
        WHEN 'scoring' THEN 'Scoring'
        WHEN 'scoring chart' THEN 'Scoring Chart'
        WHEN 'screening questions' THEN 'Screening Questions'
        WHEN 'seizures' THEN 'Seizures'
        WHEN 'sensation' THEN 'Sensations'
        WHEN 'sensation for light touch' THEN 'Sensation for Light Touch'
        WHEN 'sensation in the upper and lower extremities' THEN 'Sensation in the Upper and Lower Extremities'
        WHEN 'sensations' THEN 'Sensations'
        WHEN 'sensory' THEN 'Sensory'
        WHEN 'sensory exam' THEN 'Sensory Examination'
        WHEN 'sensory examination' THEN 'Sensory Examination'
        WHEN 'sensory functions' THEN 'Sensory Functions'
        WHEN 'sensory testing' THEN 'Sensory Examination'
        WHEN 'serial 7s, stop after 5 answers, spell word backwards score' THEN 'Serial 7S, Stop After 5 Answers, Spell Word Backwards Score'
        WHEN 'serial number' THEN 'Serial Number'
        WHEN 'severity of symptoms' THEN 'Severity of Symptoms'
        WHEN 'shift' THEN 'Shift'
        WHEN 'short term body weight goal' THEN 'Short Term Body Weight Goal'
        WHEN 'short term memory' THEN 'Short Term Memory'
        WHEN 'shoulder' THEN 'Shoulder'
        WHEN 'shoulder joint' THEN 'Shoulder Joint'
        WHEN 'shoulder-elbow' THEN 'Shoulder-Elbow'
        WHEN 'signs of abuse' THEN 'Signs of Abuse'
        WHEN 'signs/symptoms that limit ambulation' THEN 'Signs/Symptoms That Limit Ambulation'
        WHEN 'sinuses' THEN 'Sinuses'
        WHEN 'sitting and reading' THEN 'Sitting and Reading'
        WHEN 'sitting and talking to someone' THEN 'Sitting and Talking to Someone'
        WHEN 'sitting inactive in a public place (e.g. a theater/meeting)' THEN 'Sitting Inactive in a Public Place (E.G. a Theater/Meeting)'
        WHEN 'sitting quietly after a lunch without alcohol' THEN 'Sitting Quietly After a Lunch Without Alcohol'
        WHEN 'skin' THEN 'Skin Examination'
        WHEN 'skin examination' THEN 'Skin Examination'
        WHEN 'sleep disturbance (especially insomnia)' THEN 'Sleep Disturbance (Especially Insomnia)'
        WHEN 'sleep exam' THEN 'Sleep Exam'
        WHEN 'sleep study' THEN 'Sleep Study'
        WHEN 'snellen test left eye' THEN 'Snellen Test Left Eye'
        WHEN 'snellen test right eye' THEN 'Snellen Test Right Eye'
        WHEN 'soda' THEN 'Soda'
        WHEN 'solu-medrol in 250cc ns' THEN 'Solu-Medrol in 250CC NS'
        WHEN 'somatic sensory' THEN 'Somatic Sensory'
        WHEN 'spasm' THEN 'Spasm'
        WHEN 'spasticity scales' THEN 'Spasticity Scales'
        WHEN 'special diet' THEN 'Special Diet'
        WHEN 'specific gravity' THEN 'Specific Gravity'
        WHEN 'speech' THEN 'Speech'
        WHEN 'speech and language' THEN 'Speech and Language'
        WHEN 'speech/language' THEN 'Speech/Language'
        WHEN 'spinal examination' THEN 'Spinal Examination'
        WHEN 'spinal sensory level is' THEN 'Spinal Sensory Level Is'
        WHEN 'spine' THEN 'Spine'
        WHEN 'spontaneous narrative discourse' THEN 'Spontaneous Narrative Discourse'
        WHEN 'squeeze test' THEN 'Squeeze Test'
        WHEN 'stability' THEN 'Stability'
        WHEN 'start of care' THEN 'Start of Care'
        WHEN 'sternocleidomastoid muscle' THEN 'Sternocleidomastoid Muscle'
        WHEN 'sternomastoid' THEN 'Sternomastoid'
        WHEN 'straight leg raising test' THEN 'Straight Leg Raising Test'
        WHEN 'strength' THEN 'Strength'
        WHEN 'strength and tone' THEN 'Strength and Tone'
        WHEN 'strength right/left le' THEN 'Strength Right/Left LE'
        WHEN 'strength right/left ue' THEN 'Strength Right/Left UE'
        WHEN 'subjective pain scale' THEN 'Subjective Pain Scale'
        WHEN 'sudoscan' THEN 'Sudoscan'
        WHEN 'suicidal ideations' THEN 'Suicidal Ideations'
        WHEN 'suicidal thoughts or attempts, hopelessness' THEN 'Suicidal Thoughts or Attempts, Hopelessness'
        WHEN 'suicidality/homicidaility' THEN 'Suicidality/Homicidaility'
        WHEN 'summary' THEN 'Summary'
        WHEN 'supervising md (gilenya)' THEN 'Supervising MD (Gilenya)'
        WHEN 'supervising md (jtp)' THEN 'Supervising MD (JTP)'
        WHEN 'supervising physician' THEN 'Supervising Physician'
        WHEN 'symbol digit modality test (sdmt)' THEN 'Symbol Digit Modality Test (SDMT)'
        WHEN 'symptoms' THEN 'Symptoms'
        WHEN 'systemic' THEN 'Systemic'
        WHEN 'tandem examination' THEN 'Tandem Examination'
        WHEN 'tandem gait' THEN 'Tandem Gait'
        WHEN 'tandem walk' THEN 'Tandem Walk'
        WHEN 'temp' THEN 'Temp'
        WHEN 'tenderness to palpation' THEN 'Tenderness to Palpation'
        WHEN 'test' THEN 'Test'
        WHEN 'test of adolescent/adult word finding2 (tawf2)' THEN 'Test of Adolescent/Adult Word Finding2 (TAWF2)'
        WHEN 'testing measures and methods' THEN 'Testing Measures and Methods'
        WHEN 'testing scores' THEN 'Testing/Scores'
        WHEN 'testing/scores' THEN 'Testing/Scores'
        WHEN 'the romberg test is' THEN 'The Romberg Test Is'
        WHEN 'there is' THEN 'There Is'
        WHEN 'thi' THEN 'THI'
        WHEN 'thoracic spine' THEN 'Thoracic Spine'
        WHEN 'thought' THEN 'Thoughts'
        WHEN 'thought content' THEN 'Thought Content'
        WHEN 'thought process' THEN 'Thought Process'
        WHEN 'thought processes' THEN 'Thought Processes'
        WHEN 'thoughts' THEN 'Thoughts'
        WHEN 'throat' THEN 'Throat'
        WHEN 'throat exam' THEN 'Throat Exam'
        WHEN 'tilt' THEN 'Tilt'
        WHEN 'time walk' THEN 'Time Walk'
        WHEN 'timed visit' THEN 'Timed Visit'
        WHEN 'tinel''s compression' THEN 'Tinel''s Compression'
        WHEN 'tinel''s sign' THEN 'Tinel''s Sign'
        WHEN 'tingling/numbness' THEN 'Tingling/Numbness'
        WHEN 'toes' THEN 'Toes'
        WHEN 'tolerance for activities' THEN 'Tolerance for Activities'
        WHEN 'tone' THEN 'Tone'
        WHEN 'tone and gait' THEN 'Tone and Gait'
        WHEN 'tongue' THEN 'Tongue'
        WHEN 'toradol' THEN 'Toradol'
        WHEN 'torticollis' THEN 'Torticollis'
        WHEN 'total score' THEN 'Total Score'
        WHEN 'total score (cognitive impairment<=20)' THEN 'Total Score (Cognitive Impairment<=20)'
        WHEN 'total time' THEN 'Total Time'
        WHEN 'touch pre-infusion checklist' THEN 'Touch Pre-Infusion Checklist'
        WHEN 'trapezius tenderness' THEN 'Trapezius Tenderness'
        WHEN 'treatment provided' THEN 'Treatment Provided'
        WHEN 'treatment stimulability probe' THEN 'Treatment Stimulability Probe'
        WHEN 'tremor' THEN 'Tremors'
        WHEN 'tremor-face/jaw' THEN 'Tremor-Face/Jaw'
        WHEN 'tremors' THEN 'Tremors'
        WHEN 'trigeminal' THEN 'Trigeminal'
        WHEN 'trochlear' THEN 'Trochlear'
        WHEN 'tuning fork exam' THEN 'Tuning Fork Exam'
        WHEN 'two point discrimination' THEN 'Two Point Discrimination'
        WHEN 'tylenol' THEN 'Tylenol'
        WHEN 'tympanometry/immittance' THEN 'Tympanometry/Immittance'
        WHEN 'tysabri in 100ml ns' THEN 'Tysabri in 100mL NS'
        WHEN 'ubw' THEN 'UBW'
        WHEN 'upper extremities' THEN 'Upper Extremities'
        WHEN 'upper motor neuron signs' THEN 'Upper Motor Neuron Signs'
        WHEN 'urethra' THEN 'Urethra'
        WHEN 'urobilinogen' THEN 'Urobilinogen'
        WHEN 'uterus' THEN 'Uterus'
        WHEN 'v' THEN 'Cranial Nerve V'
        WHEN 'v, vii' THEN 'Cranial Nerve V and VII'
        WHEN 'vagina' THEN 'Vagina'
        WHEN 'vascular' THEN 'Vascular Exam'
        WHEN 'vascular exam' THEN 'Vascular Exam'
        WHEN 'verbal expression' THEN 'Verbal Expression'
        WHEN 'vertebral spine tenderness' THEN 'Vertebral Spine Tenderness'
        WHEN 'vestibular' THEN 'Vestibular'
        WHEN 'vestibular evoked myogenic potential tests' THEN 'Vestibular Evoked Myogenic Potential Tests'
        WHEN 'vestibulo-ocular/positional and positioning maneuvers' THEN 'Vestibulo-Ocular/Positional and Positioning Maneuvers'
        WHEN 'vestibulo-spinal' THEN 'Vestibulo-Spinal'
        WHEN 'vi' THEN 'Cranial Nerve VI'
        WHEN 'vibration' THEN 'Vibration'
        WHEN 'video head impulse test' THEN 'Video Head Impulse Test'
        WHEN 'vii' THEN 'Cranial Nerve VII'
        WHEN 'viii' THEN 'Cranial Nerve VIII'
        WHEN 'visit count' THEN 'Visit Count'
        WHEN 'visit status' THEN 'Visit Status'
        WHEN 'visit summary' THEN 'Visit Summary'
        WHEN 'visit type: daily note' THEN 'Visit Type: Daily Note'
        WHEN 'visual (optic) function' THEN 'Visual (Optic) Function'
        WHEN 'visual acuity' THEN 'Visual Acuity'
        WHEN 'visual disturbance' THEN 'Visual Disturbance'
        WHEN 'visual evoked potential (vep)' THEN 'Visual Evoked Potential (VEP)'
        WHEN 'visual fields' THEN 'Visual Fields'
        WHEN 'visual hallucinations' THEN 'Visual Hallucinations'
        WHEN 'visual/optic functions' THEN 'Visual (Optic) Function'
        WHEN 'visuospatial/executive' THEN 'Visuospatial/Executive'
        WHEN 'vitamins/herbs/supplements' THEN 'Vitamins/Herbs/Supplements'
        WHEN 'vitamins/minerals' THEN 'Vitamins/Minerals'
        WHEN 'vng' THEN 'VNG'
        WHEN 'vocal characteristics' THEN 'Vocal Characteristics'
        WHEN 'vocal hygiene: vocally abusive behaviors and irritants' THEN 'Vocal Hygiene: Vocally Abusive Behaviors and Irritants'
        WHEN 'vocal hygiene: voice use' THEN 'Vocal Hygiene: Voice Use'
        WHEN 'voice quality/ability to communicate' THEN 'Voice Quality/Ability to Communicate'
        WHEN 'vs_test' THEN 'Vs_Test'
        WHEN 'walking' THEN 'Walking'
        WHEN 'watching tv' THEN 'Watching TV'
        WHEN 'water' THEN 'Water'
        WHEN 'weight' THEN 'Weight'
        WHEN 'weight evaluation' THEN 'Weight Evaluation'
        WHEN 'weight history' THEN 'Weight History'
        WHEN 'weight loss or gain (especially loss)' THEN 'Weight Loss or Gain (Especially Loss)'
        WHEN 'what is the year, season, date, day, month' THEN 'What Is the Year, Season, Date, Day, Month'
        WHEN 'where are we, state, country, town, hospital, floor' THEN 'Where Are We, State, Country, Town, Hospital, Floor'
        WHEN 'with' THEN 'With'
        WHEN 'wrist' THEN 'Wrist'
        WHEN 'wrist-hand' THEN 'Wrist and Hand'
        WHEN 'write a sentence score' THEN 'Write a Sentence Score'
        WHEN 'written expression' THEN 'Written Expression'
        WHEN 'xi' THEN 'Cranial Nerve XI'
        WHEN 'xii' THEN 'Cranial Nerve XII'
        WHEN 'xray/mri/imaging' THEN 'Xray/MRI/Imaging'
        WHEN 'zantac' THEN 'Zantac'
        WHEN 'zofran' THEN 'Zofran'
        ELSE exam_name_cleaned
    END AS exam_name_std
FROM structurally_cleaned;
